import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";


const cinzel = Cinzel({
  subsets: ['latin'],
  variable: '--font-cinzel', // This creates a CSS variable
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
